name: Update blogs and stats
on:
  schedule:
    - cron: '0 1 * * *' # every 24 hours
  push:
    branches:
      - main
jobs:
  # Update template with blogs and Publish to main README.md
  update-template-with-blog:
    name: Update this repo's Template with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Update TEMPLATE.md
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          readme_path: ./TEMPLATE.md
          feed_list: "https://aitikgupta.github.io/feed.xml"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@master
        with:
          token: ${{ secrets.USER_TOKEN }}
      - name: Update README.md
        run: |
          git stash
          git pull
          git stash pop
          if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Update README"
          git push
          fi